name: Workflow ReactJS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Start project and check
        run: |
          nohup npm start > server.log 2>&1 &
          sleep 5
          curl -f http://localhost:3000 || (tail -n 50 server.log && exit 1)
